// <auto-generated />
using System;
using Car_Database.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Car_Database.Migrations
{
    [DbContext(typeof(CarDataContext))]
    partial class CarDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("Car_Database.Model.CarMake", b =>
                {
                    b.Property<int>("CarMakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.HasKey("CarMakeId");

                    b.ToTable("CarMakes");
                });

            modelBuilder.Entity("Car_Database.Model.CarModel", b =>
                {
                    b.Property<int>("CarModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarMakeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasKey("CarModelId");

                    b.HasIndex("CarMakeId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("Car_Database.Model.Ownership", b =>
                {
                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CarModelId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("Ownerships");
                });

            modelBuilder.Entity("Car_Database.Model.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Car_Database.Model.CarModel", b =>
                {
                    b.HasOne("Car_Database.Model.CarMake", "CarMake")
                        .WithMany()
                        .HasForeignKey("CarMakeId");
                });

            modelBuilder.Entity("Car_Database.Model.Ownership", b =>
                {
                    b.HasOne("Car_Database.Model.CarModel", "CarModel")
                        .WithMany("Ownerships")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Database.Model.Person", "Person")
                        .WithMany("Ownerships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
